[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuizQuestions = "612c44de-1021-4a21-84fb-7261cf5eb2d4"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
